### ISSUE TITLE
Cannot build remoteswap modules and server

### ISSUE THREAD

**Issue by yashlala** [uclasystem/hermit#1]
Hi Yifan!

I'm having some issues building this version of Hermit. 

## Environment

- Ubuntu 20.04
- gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- Mellanox OFED driver: 5.4-3.1.0.0-LTS
- RoCE hardware via Mellanox ConnectX-5

(All are the same as in the Hermit README)

## To reproduce

Follow the installation instructions (update GRUB, install MLNX driver, install the kernel, restart openibd, reboot). Then try to `make` in `remoteswap/server` or `remoteswap/client`. 

### Remoteswap Server Build Errors

In `rswap-server.cpp:466`, the server references a `(struct context *)->cq_poller_thread`.
`struct context` is defined in `rswap_server.hpp:59`, and doesn't have a `cq_poller_thread`.

## Remoteswap Client Build Errors

Build errors attached at: https://gist.github.com/yashlala/d55f74d8706b2928df682d853582f118

------

Does this repository's version of Hermit build cleanly on your end? Is there another "canonical" version of Hermit to benchmark against? 

Many thanks in advance.

**Comment by ivanium** [comment]
Hi Yash,

Thank you for reaching out. We did miss a line in the header file. I have pushed a fix that should solve the issue. Please feel free to try it out and let me know if you have further issues.

Best regards,
Yifan

**Comment by yashlala** [comment]
Dear Yifan, 

Thank you! The server builds perfectly now. I can't test the client module yet due to another problem -- I'll raise an issue for that (or resolve it on my own), then come back to resolve this. 

Regards, 

Yash
