### ISSUE TITLE
Machine fails to reboot after kernel installation

### ISSUE THREAD

**Issue by sosson97** [uclasystem/hermit#3]
Hi,

I have been trying to install Hermit on Cloudlab, but I found that my machine keeps failing to boot after compiling and installing the kernel. As far as I know, this usually happens when the kernel config is not compatible with a machine. But I have no clue what is wrong with the given config file. Could I get any help to fix this issue?

Testing environment:
I used Hermit-NSDI23 profile in Cloudlab and used bare metal c6525-100g machine. 

Installation:
I followed the steps in [this section](https://github.com/uclasystem/hermit/tree/master#build--install-hermit) up to (2). The only difference is that I used "Advanced options for Ubuntu>Ubuntu, with Linux 5.14.0-rc5" instead of "Advanced options for Ubuntu>Ubuntu, with Linux 5.14-rc5" for the default boot target as that was the name of the boot image in my system.

Symptoms:
The machine falls into an infinite reboot process, shown as "changing" in the Cloudlab experiment dashboard.

**Comment by ivanium** [comment]
Hi sosson97,

Thank you for your interest in our work. Could you check the "console" of the machine on Cloudlab and attach the log/screenshot if it shows anything? I can take a look at the issue further soon.

Thank you,
Yifan

**Comment by sosson97** [comment]
Hi Yifan,

Thanks for the quick response. Unfortunately, I couldn't see any information in the Console menu. Instead, I found out that the issue was fixed when I used "config-with-rdma-driver" instead of "config". It seems like "config" file doesn't include some drivers required for c6525-100g machines. Have you ever checked Hermit works with both configs? I've not been able to test it myself because now I am stuck at the OFED driver installation.

**Comment by ivanium** [comment]
Hi sosson97,

It's great to hear you can boot the machine now. Yes, please just use "config" if you have installed / will install the OFED driver by yourself. If the kernel cannot boot when compiled with "config", I suggest you try "/boot/config-5.10.0" first.

To elaborate, the main difference between "config" and "config-with-rdma-driver" is that the latter enables kernel RDMA drivers (mlx4 and mlx5) for those machines without any OFED driver. As those kernel RDMA drivers are incompatible with OFED drivers, you will not be able to install OFED driver with kernel compile with "config-with-rdma-driver". So there are mainly two options:

1. You can go with the current kernel without OFED driver. Your probably need some userspace libraries and tools as well:

```bash
sudo apt install -y infiniband-diags opensm libibverbs-dev librdmacm-dev perftest
sudo apt install -y rdma-core ibutils ibverbs-utils rdmacm-utils # ibverbs-provider 

sudo systemctl enable opensm
sudo systemctl start opensm
```

Reboot the machine and you should be able to connect with RDMA.

2. If you want to go with OFED drivers, you may try compiling kernel with "/boot/config-5.10.0":

```bash
cp /boot/config-5.10.0 .config
# compile and install the kernel again
```

Then you should be able to install OFED drivers and continue.

I hope you find these helpful and feel free to reach out if you have further questions.

Best regards,
Yifan

**Comment by sosson97** [comment]
Thank you so much!

**Comment by BarrinXu** [comment]
Hi @sosson97 ,

Did you finally setup successfully? Could you share your choice of setup?
I am also trying to build hermit on cloudlab via Hermit-NSDI23 profile.

- Build kernel with "/boot/config-5.10.0"

	- Install Mellanox OFED driver: 5.4-3.1.0.0: Fail to install the OFED driver.
	- Install Mellanox OFED driver: 5.4-3.7.5.0: Install the OFED driver successfully, but fail to compile the rswap-client.ko.

- Build kernel with "config-with-rdma-driver"
If I use "config-with-rdma-driver", I can successfully install those "userspace libraries and tools" mentioned above, and compile the client side and server side. However, I encounter a strange problem when the client tries to connect to the server.
Symptoms:
I specified SWAP_PARTITION_SIZE="48", and theoretically dmesg should output "rswap_request_for_chunk, Got **12** chunks from memory server." However, dmesg outputs "rswap_request_for_chunk, Got **6** chunks from memory server."
Then, when I try to run a docker container and use the cgroup to limit the local memory, there occurs an OOM killing of the container.

I'm willing to provide more detailed logs if anyone has encountered similar issues or has further suggestions.
Thanks.
