### ISSUE TITLE
Cannot install the OFED driver and build the remoteswap client module

### ISSUE THREAD

**Issue by BarrinXu** [uclasystem/hermit#4]
Hi, I'm having some troubles building the OFED driver and the client module after successfully install the Linux 5.14.0-rc5 kernel.
# Environment
Cloudlab c6525-25g
Ubuntu 20.04, with Linux 5.14.0-rc5, built by the config file `linux-5.14-rc5/config-cloudlab`.
# Issues

- Failed to install Mellanox OFED driver: 5.4-3.1.0.0-LTS (the same version in the [README.md](https://github.com/uclasystem/hermit#readme))
	- A simple log: [mlnx_ofed_iso.1430.log](https://github.com/uclasystem/hermit/files/12450558/mlnx_ofed_iso.1430.log)
	- A detailed log: [mlnx-ofed-kernel.debbuild.log](https://github.com/uclasystem/hermit/files/12450570/mlnx-ofed-kernel.debbuild.log) (The first error happens at Line 1920 in the log)

- Install Mellanox OFED driver: 5.4-3.7.5.0-LTS successfully, but failed to build the client side module.
	- The build log: [client_make_log.txt](https://github.com/uclasystem/hermit/files/12450663/client_make_log.txt)

Many thanks in advance.

**Comment by yashlala** [comment]
I'm having similar issues building the OFED driver. The full contents of my MLNX build and log directories are [here](https://drive.google.com/file/d/1OS59wvx6BROOKwjn3moozqEv9D_MLdsv/view?usp=sharing). 


## Environment  

- Ubuntu 20.04
- gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- Mellanox OFED driver: 5.4-3.1.0.0-LTS
- RoCE hardware via Mellanox ConnectX-5

(identical to the Hermit README)

## To Reproduce

Follow the README for the following steps: 

- Change grub parameters on host server 
- Build and install Hermit server, and reboot. 
- Attempt to install the MLNX_OFED drivers as described in the README; ie: 
  ```
  # Download the MLNX OFED driver for the Ubuntu 20.04
  wget https://content.mellanox.com/ofed/MLNX_OFED-5.4-3.1.0.0/MLNX_OFED_LINUX-5.4-3.1.0.0-ubuntu20.04-x86_64.tgz
  tar xzf MLNX_OFED_LINUX-5.4-3.1.0.0-ubuntu20.04-x86_64.tgz
  cd MLNX_OFED_LINUX-5.4-3.1.0.0-ubuntu20.04-x86_64

  # Install the MLNX OFED driver against linux-5.14-rc5
  sudo ./mlnxofedinstall --add-kernel-support --force
  ```

This will yield the following output: 

```
$ sudo ./mlnxofedinstall --add-kernel-support --force
Note: This program will create MLNX_OFED_LINUX TGZ for ubuntu20.04 under /tmp/MLNX_OFED_LINUX-5.4-3.1.0.0-5.14.0-rc5 directory.
See log file /tmp/MLNX_OFED_LINUX-5.4-3.1.0.0-5.14.0-rc5/mlnx_iso.1051_logs/mlnx_ofed_iso.1051.log

Checking if all needed packages are installed...
Building MLNX_OFED_LINUX DEBS . Please wait...

ERROR: Failed executing "MLNX_OFED_SRC-5.4-3.1.0.0/install.pl --tmpdir /tmp/MLNX_OFED_LINUX-5.4-3.1.0.0-5.14.0-rc5/mlnx_iso.1051_logs --kernel-only --kernel 5.14.0-rc5 --kernel-sources /lib/modules/5.14.0-rc5/build --builddir /tmp/MLNX_OFED_LINUX-5.4-3.1.0.0-5.14.0-rc5/mlnx_iso.1051 --without-dkms --force --without-debug-symbols --build-only --distro ubuntu20.04"
ERROR: See /tmp/MLNX_OFED_LINUX-5.4-3.1.0.0-5.14.0-rc5/mlnx_iso.1051_logs/mlnx_ofed_iso.1051.log
Failed to build MLNX_OFED_LINUX for 5.14.0-rc5
```

`/tmp/MLNX_OFED_LINUX-5.4-3.1.0.0-5.14.0-rc5/mlnx_iso.1051_logs/mlnx_ofed_iso.1051.log`
indicates that the `mlnx-ofed-kernel` build fails. I chased that log message to 
`/tmp/MLNX_OFED_LINUX-5.4-3.1.0.0-5.14.0-rc5/mlnx_iso.1051_logs/OFED.1249.logs/mlnx-ofed-kernel.debbuild.log`, 
which is similar to @BarrinXu's log.

**Comment by ivanium** [comment]
Hi, 

Thank you all for raising the issue. I will check on my side and get back to you soon.

Best wishes,
Yifan

**Comment by hoaaosnw** [comment]
Same issue

**Comment by yashlala** [comment]
Hi All -- any progress on this issue? Has anyone figured out a workaround?

**Comment by RussellWang9** [comment]
I encountered the same issue as @BarrinXu and @yashlala.

I failed to build and install Mellanox OFED driver 5.4-3.1.0.0-LTS, which produced the same log as @BarrinXu.

I was able to successfully install Mellanox OFED driver 5.4-3.7.5.0-LTS, but then failed to build the client kernel module just as @BarrinXu did, producing the very same log. I believe the problem is the wrong order of include directories. Editing the following line in `remoteswap/client/Makefile` could resolve this issue.
```
LINUXINCLUDE :=                 \
	$(LINUXINCLUDE)         \
	-I$(OFA_INCLUDE)        \
	-I$(RSWAP_ROOT_PATH)/..

**Comment by BarrinXu** [comment]
> I encountered the same issue as @BarrinXu and @yashlala.
> 
> I failed to build and install Mellanox OFED driver 5.4-3.1.0.0-LTS, which produced the same log as @BarrinXu.
> 
> I was able to successfully install Mellanox OFED driver 5.4-3.7.5.0-LTS, but then failed to build the client kernel module just as @BarrinXu did, producing the very same log. I believe the problem is the wrong order of include directories. Editing the following line in `remoteswap/client/Makefile` could resolve this issue.
> 
> ```
> LINUXINCLUDE :=                 \
> 	$(LINUXINCLUDE)         \
> 	-I$(OFA_INCLUDE)        \
> 	-I$(RSWAP_ROOT_PATH)/..
> ```



> I encountered the same issue as @BarrinXu and @yashlala.
> 
> I failed to build and install Mellanox OFED driver 5.4-3.1.0.0-LTS, which produced the same log as @BarrinXu.
> 
> I was able to successfully install Mellanox OFED driver 5.4-3.7.5.0-LTS, but then failed to build the client kernel module just as @BarrinXu did, producing the very same log. I believe the problem is the wrong order of include directories. Editing the following line in `remoteswap/client/Makefile` could resolve this issue.
> 
> ```
> LINUXINCLUDE :=                 \
> 	$(LINUXINCLUDE)         \
> 	-I$(OFA_INCLUDE)        \
> 	-I$(RSWAP_ROOT_PATH)/..
> ```

Thanks for sharing the solution. @wzx-ipads

**Comment by nnurlan008** [comment]
Hi,

I am getting an error while trying to make connection between memory and compute nodes:

`insmod: ERROR: could not insert module ./rswap-client.ko: Unknown symbol in module`

dmesg:
```
[  388.831814] rswap_client: Unknown symbol __rdma_create_kernel_id (err -2)
[  388.831857] rswap_client: Unknown symbol __ib_alloc_cq (err -2)
[  670.603858] Adding 4194300k swap on /users/Nurlan/swapfile1.  Priority:-2 extents:1194 across:392921088k SSFS
[  670.617860] rswap_client: Unknown symbol __rdma_create_kernel_id (err -2)
[  670.617889] rswap_client: Unknown symbol __ib_alloc_cq (err -2)
[124090.201749] Adding 4194300k swap on /users/Nurlan/swapfile1.  Priority:-2 extents:862 across:189256036k SSFS
[124090.212190] rswap_client: Unknown symbol __rdma_create_kernel_id (err -2)
[124090.212221] rswap_client: Unknown symbol __ib_alloc_cq (err -2)
```

Specs:
Ubuntu 20
Mellanox OFED driver 5.4-3.1.0.0-LTS
Memory: 64GB
CPU: Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz

Has anyone encountered similar issue?

Thanks in advance
